### ISSUE TITLE
I do not have GPU

### ISSUE THREAD

**Issue by bournes** [Conchylicultor/DeepQA#3]
He can be used in the absence of GPU server?

**Comment by Conchylicultor** [comment]
If TensorFlow doesn't detect a GPU, it should automatically switch to CPU mode. Otherwise, use the `--device cpu` flag when running the program to force the cpu mode. It should work but the training will  last much longer.

Be careful though, TensorFlow unroll the recurent network so it can quickly take a lot of RAM, depending of the parameters.
