### ISSUE TITLE
Cannot run tensorboard while training [Windows]

### ISSUE THREAD

**Issue by eschnou** [Conchylicultor/DeepQA#30]
On Windows, running tensorboard while training leads to a crash when attempting so save model at checkpoint. Not sure if this can be solved on DeepQA side, maybe more a tensorboard issue (it should avoid locking the files).

`Traceback (most recent call last):
  File "D:\Workspace\tools\python\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1021, in _do_call
    return fn(*args)
  File "D:\Workspace\tools\python\lib\site-packages\tensorflow\python\client\ses
sion.py", line 1003, in _run_fn
    status, run_metadata)
  File "D:\Workspace\tools\python\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\Workspace\tools\python\lib\site-packages\tensorflow\python\framework\
errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: D:\Works
pace\DeepQA\save/model\model.ckpt.tempstate9018892726155787139 to: D:\Workspace\
DeepQA\save/model\model.ckpt : Access is denied.
; Input/output error`

**Comment by Conchylicultor** [comment]
I'm not sure I can help you. The windows version is still fairly recent so may be unstable. Another possibility would be the saving format for the model which use saver V1 and may not be compatible with windows. However, it seems unlikely because the saver should not affect tensorboard but only the checkpoints model.
For the error message, it looks more like a permission issue, maybe tensorboard has to be run in administration mode ?
Last possibility would be to isolate which generated files which causes the problem and submit an issue on the official repository.

**Comment by jeromerg** [comment]
I have exactely the same problem. What was the fix?

**Comment by scign** [comment]
I have found that I get this error if I have an Explorer window also watching the folder. I close the Explorer window and the error stopped appearing. That leads me to think that it's Explorer that is locking the file and TensorBoard gets locked out.
